<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('bills', function (Blueprint $table) {
            $table->id();
            
            $table->string('bill_number', 50)->unique();
            // Format: BILL-20260428-0001 — generated by service
            
            $table->enum('status', ['processing', 'ready', 'delivered'])
                ->default('processing');
            // processing = items being entered, not finalized
            // ready = saved, awaiting customer pickup
            // delivered = handed to customer
            
            $table->foreignId('created_by')->constrained('employees');
            // cashier who created this bill
            
            $table->unsignedBigInteger('editor_id')->nullable();
            // assigned editor for this bill (may differ from cashier)
            // NO FK — handled in service layer
            
            $table->decimal('commission_pct', 5, 2)->nullable();
            // rate applied when bill was created (snapshot)
            // NULL = no commission
            
            $table->boolean('is_commission_applicable')->default(true);
            // false = commission disabled for this bill (override)
            
            $table->enum('payment_method', ['cash', 'card', 'split'])
                ->default('cash');
            // split = partial cash + partial card
            
            $table->string('card_ref', 100)->nullable();
            // card transaction reference
            
            $table->decimal('subtotal', 10, 2)->default(0.00);
            $table->decimal('discount_amount', 10, 2)->default(0.00);
            $table->decimal('after_discount', 10, 2)->default(0.00);
            // = subtotal - discount_amount
            
            $table->decimal('paid_amount', 10, 2)->default(0.00);
            // amount paid by customer
            
            $table->decimal('balance_due', 10, 2)->default(0.00);
            // = after_discount - paid_amount (for advance/balance scenarios)
            
            $table->unsignedBigInteger('advance_ref_bill_id')->nullable();
            // FK to previous bill IF this is a "balance" bill
            // allows linking advance payment to balance payment
            
            $table->text('notes')->nullable();
            
            $table->timestamps();

            // Indexes for query performance
            $table->index('bill_number');
            $table->index('status');
            $table->index('created_by');
            $table->index('editor_id');
            $table->index('created_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('bills');
    }
};
